name: galileo-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - gdal
  - rasterio
  - fiona
  - geopandas
  - h5py
  - rioxarray
  - numpy=1.26
  - scikit-learn
  - matplotlib
  - pandas=2.1
  - pip
  - pip:
      - wandb==0.16.3
      - einops==0.7.0
      - torch==2.2.1
      - torchvision==0.17.1
      - torchmetrics==1.3.2
      - earthengine-api==0.1.391
      - tqdm==4.66.2
      - geobench==1.0.0
      - types-requests
      - fast_pytorch_kmeans
      - satlaspretrain-models
      - timm
      - breizhcrops
      - ruff==0.2.0
      - mypy==1.8.0
